name: Card detect demo
version: 1.1.0

port: 8080

tmp_folder: ./tmp
storage_folder: ./storage

onnx:
  path_runtime: ./lib/onnx_18/libonnxruntime.so
  path_model: ./models/yolov8m-card-detect.onnx

is_log_time: true